### ISSUE TITLE
Recursive walk to parent at level

### ISSUE THREAD

**Issue by ben-jacobs** [KnightMoveSolutions/Hierarchical#1]
Great little library - I'm finding it really useful (albeit a little bit cumbersome with all the wrapper classes, but that's understandable).

Is there any easy way to walk from a node up the parents until it reaches a parent at a particular level (i.e. ancestor at level x)?

At the moment I'm just using a recursive Func<T,T> and it works fine (and could probably just make an extension method), but just wasn't sure if you'd thought about any other options.

**Comment by rickyricky74** [comment]
It's been a little over two years since this issue has been posted and it is thoroughly unacceptable for me to not respond. However, at the end of 2017 I lost my credentials and 2FA backup codes to this repo. A few months ago I found my backup codes written on a card somewhere and was finally able to get back in. I didn't know this issue had been posted so I am very, very sorry that I did not catch this. 

I'm guessing this is probably a non-issue now but I am going to respond anyway. 

The way to walk up the parent with v1.0 is to create your own recursive method or extension method as you stated. I've done this myself when I needed to go up the ancestors but have not needed to stop at any particular ancestor or level up the tree. However, given this issue, I included it as part of my v2.0 library implemented with .NET Core 3 now that I finally caught up to upgrading the library. I also got rid of the nested generic type references. Working with the library is much cleaner now. I recommend reading the updated README.md file if you're still interested. 

I really appreciate the compliment on the library. I didn't think it got noticed much at all. Sorry again and I appreciate your patience and understanding.

Ricardo
